---
- name: Configure DFS Cluster
  hosts: dfs_primary
  gather_facts: false
  become_method: runas
  become: yes
  become_user: '{{ ansible_user }}'
  vars_files:
    -   play_vars.yml
    -   ../../cred.yml
  tasks:
    - include_tasks: 'tasks/group.yml'
