---
- name: Configure DFS Cluster
  hosts: dc
  gather_facts: false
  become_method: runas
  become: yes
  become_user: '{{ ansible_user }}'
  vars_files:
    -   play_vars.yml
    -   cred.yml
  tasks:
    - include_tasks: 'tasks/ping.yml'
    #- include_tasks: 'tasks/group.yml'
