---
- name: Import Module
  win_shell: |
    Install-Module -Name ActiveDirectoryDsc -Force
    Import-Module -Name ActiveDirectoryDsc

- name: AD Group
  win_dsc:
    resource_name: ADGroup
    GroupName: infotech-admins-new
    GroupScope: Global
    Category: Security
    Path: 'OU=Groups,DC=win,DC=infotech,DC=com'
    Ensure: Present
    PsDscRunAsCredential_username: '{{ansible_user}}'
    PsDscRunAsCredential_password: '{{ansible_password}}'

