- name: Provide OU Permission
  win_dsc:
    resource_name: ADObjectPermissionEntry
    Path: '{{OUPATH}}'
    IdentityReference: win\dc1$
    AccessControlType: 'Allow'
    ActiveDirectoryRights: 'ReadProperty'
    ActiveDirectorySecurityInheritance: 'None'
    ObjectType: '00000000-0000-0000-0000-000000000000'
    InheritedObjectType: '00000000-0000-0000-0000-000000000000'
    Ensure: Present
    PsDscRunAsCredential_username: '{{ansible_user}}'
    PsDscRunAsCredential_password: '{{ansible_password}}'
